---
title: "CviMVP_oyster_GO_plotting"
author: "Camille Rumberger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# wd
setwd("~/Documents/GitHub/MVP_oyster_GO")

# libraries
library(ggplot2) # for plotting
library(raster) # for environmental pixels
library(sf) # plotting
library(rnaturalearth) # plotting
library(maps) # mapping
library(ggspatial) # mapping
library(ggrepel) # mapping
library(officer) # for powerpoint export/editing
library(rvg) # for converting r graphics to editable vector graphics

# data
# metadata
popsdf <- read.csv("data/IndDat/popsdf.csv")[,-1]
latlons <- read.csv("data/IndDat/seascape_latlon.csv")[,-1]

# interpolated
lea_interpolated <- readRDS("results/GO_results/lea_interpolated_go.RDS")
rda_interpolated <- readRDS("results/GO_results/rda_interpolated_go.RDS")
gf_interpolated <- readRDS("results/GO_results/gf_af_interpolated_go.RDS")
envdist_interpolated <- readRDS("results/GO_results/envdist_interpolated.RDS")

# experimental
lea_go <- read.csv("results/GO_results/offsets_LEA_expsites_2025-11-22.csv")[,-1]
rda_go <- read.csv("results/GO_results/offsets_RDA_expSites_2025-11-22.csv")[,-1]
gf_go <- read.csv("results/GO_results/offsets_GF_expSites_2025-11-24.csv")[,-1]

# seascape
lea_sea <- read.csv("results/GO_results/offsets_LEA_fullseascape_2025-11-22.csv")[,-1]
rda_sea <- read.csv("results/GO_results/offsets_RDA_fullseascape_2025-11-22.csv")[,-1]
gf_sea <- read.csv("results/GO_results/offsets_GF_fullseascape_2025-11-30.csv") # need to rerun and save
envdist <- read.csv("data/EnvDat/exp/distance_matrix_abiotic_2025-11-24.csv")[,c("X","Lewisetta","YorkRiver")] # this has both the seascape sites and the experimental sites
```


# Genomic Offset Plotting

This script is for high quality plotting and export of genomic offset prediction maps across all methods (LEA, GF, RDA, EnvDist) to an editable powerpoint with vectorized graphics. 


## Data Prep

### LEA

```{r}
# prep latlons for merging
latlons$site_name <- latlons$ID_SiteDate

## environmental distance
#########################
# rename columns
colnames(envdist) <- c("site_name", "dist_lew", "dist_yrk")

# split into seascape vs exp pops
envdist_sea <- envdist[1:27,]
envdist_exp <- envdist[28:35,]

# need latlons for the seascape sites
latlons
#########################
```


## Plotting

Now plot the genomic offsets.

### LEA

```{r}
map_lew_int_lea <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_lew, mapping = aes(fill = var1.pred, col = var1.pred)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting_lea, aes(x = Longitude_manual, y = Latitude_manual, 
                                              fill = lew_go), 
             shape = 21, size = 2) +
  geom_point(data = offsets_plotting_lea[offsets_plotting_lea$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=Longitude_manual, y=Latitude_manual, 
                                       fill = lew_go), 
             shape = 21, size = 4)+
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,0.08)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,0.08)) +
  geom_label_repel(data = offsets_plotting_lea[offsets_plotting_lea$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=Longitude_manual, y=Latitude_manual, 
                                       label = site_name),
                  nudge_x = -3,
                  nudge_y = 1,
                  fill = "white")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right')+
  labs(title = "Genomic Offset to \nLewisetta (LEA)", x = "Longitude", y = "Latitude", col = "Genomic \nOffset", fill = "Genomic \nOffset")
(map_lew_int_lea)

lew_int_lea_inset <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_lew, mapping = aes(fill = var1.pred, col = var1.pred)) +
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,0.08)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,0.08)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting_lea, aes(x = Longitude_manual, y = Latitude_manual, 
                                              fill = lew_go), 
             shape = 21, size = 5) +
  geom_point(data = offsets_plotting_lea[offsets_plotting_lea$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, fill = lew_go), 
             shape = 21, size = 7)+
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0, 0.08)) + # double check these values
  geom_point(data = offsets_plotting_lea[offsets_plotting_lea$site_name == "LEWISETTA",], 
             aes(x = longitude-0.2, y = latitude), fill = "deeppink", shape = 24, size = 7)+
  geom_label_repel(data = offsets_plotting_lea[offsets_plotting_lea$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, label = site_name),
                  nudge_x = 2.5,
                  nudge_y = 0.4,
                  fill = "white",
                  size = 9)+
  guides(fill = "none")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right') +
        xlim(-77.856476, -72.762787) +
        ylim(36.019557, 39.939163)
lew_int_lea_inset

map_yrk_int_lea <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_yrk, mapping = aes(col = var1.pred)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting_lea, aes(x = Longitude_manual, y = Latitude_manual, 
                                              fill = lew_go), 
             shape = 21, size = 2) +
  geom_point(data = offsets_plotting_lea[offsets_plotting_lea$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=longitude, y=latitude, fill = yrk_go), 
             shape = 21, size = 4)+
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,0.08)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,0.08)) +
  geom_label_repel(data = offsets_plotting_lea[offsets_plotting_lea$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=longitude, y=latitude, label = site_name),
                  nudge_x = -3,
                  nudge_y = 1,
                  fill = "white")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = "right")+
  labs(title = "Genomic Offset to \nYork River (LEA)", x = "Longitude", y = "Latitude", col = "Genomic \nOffset", fill = "Genomic \nOffset")
(map_yrk_int_lea)

yrk_int_lea_inset <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_yrk, mapping = aes(fill = var1.pred, col = var1.pred)) +
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,0.08)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,0.08)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting_lea, aes(x = Longitude_manual, y = Latitude_manual, 
                                              fill = lew_go), 
             shape = 21, size = 5) +
  geom_point(data = offsets_plotting_lea[offsets_plotting_lea$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, fill = yrk_go), 
             shape = 21, size = 9)+
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0, 0.08)) + # double check these values
  geom_point(data = offsets_plotting_lea[offsets_plotting_lea$site_name == "YORKRIVER",], 
             aes(x = longitude-0.1, y = latitude+0.1), fill = "deeppink", shape = 24, size = 7)+
  geom_label_repel(data = offsets_plotting_lea[offsets_plotting_lea$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, label = site_name),
                  nudge_x = 2.5,
                  nudge_y = 0.5,
                  fill = "white",
                  size = 9)+
  guides(fill = "none")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right') +
        xlim(-77.856476, -72.762787) +
        ylim(36.019557, 39.939163)
yrk_int_lea_inset
```

### RDA

```{r}
map_lew_int_rda <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_lew_rda, mapping = aes(fill = var1.pred, col = var1.pred)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting, aes(x = longitude, y = latitude, 
                                              fill = offset_lew_sea), 
             shape = 21, size = 2) +
  geom_point(data = offsets_plotting[offsets_plotting$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=longitude, y=latitude, 
                                       fill = offset_lew), 
             shape = 21, size = 4)+
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,3.5)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,3.5)) +
  geom_label_repel(data = offsets_plotting[offsets_plotting$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=longitude, y=latitude, 
                                       label = site_name),
                  nudge_x = -3,
                  nudge_y = 1,
                  fill = "white")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right')+
  labs(title = "Genomic Offset to \nLewisetta (RDA)", x = "Longitude", y = "Latitude", col = "Genomic \nOffset", fill = "Genomic \nOffset")
(map_lew_int_rda)

lew_int_rda_inset <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_lew_rda, mapping = aes(fill = var1.pred, col = var1.pred)) +
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,3.5)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,3.5)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting, aes(x = longitude, y = latitude, 
                                              fill = offset_lew_sea), 
             shape = 21, size = 5) +
  geom_point(data = offsets_plotting[offsets_plotting$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, 
                                       fill = offset_lew), 
             shape = 21, size = 9)+
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0, 3.5)) +
  geom_point(data = offsets_plotting[offsets_plotting$site_name == "LEWISETTA",], 
             aes(x = longitude-0.2, y = latitude), fill = "deeppink", shape = 24, size = 7)+
  geom_label_repel(data = offsets_plotting[offsets_plotting$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, label = site_name),
                  nudge_x = 2.5,
                  nudge_y = 0.5,
                  fill = "white",
                  size = 9)+
  guides(fill = "none")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right') +
        xlim(-77.856476, -72.762787) +
        ylim(36.019557, 39.939163)
lew_int_rda_inset

map_yrk_int_rda <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_yrk_rda, mapping = aes(col = var1.pred, fill = var1.pred)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting, aes(x = longitude, y = latitude, 
                                              fill = offset_yrk_sea), 
             shape = 21, size = 2) +
  geom_point(data = offsets_plotting[offsets_plotting$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=longitude, y=latitude, fill = offset_yrk), 
             shape = 21, size = 4)+
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,3.5)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,3.5)) +
  geom_label_repel(data = offsets_plotting[offsets_plotting$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=longitude, y=latitude, 
                                       label = site_name),
                  nudge_x = -3,
                  nudge_y = 1,
                  fill = "white")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = "right")+
  labs(title = "Genomic Offset to \nYork River (RDA)", x = "Longitude", y = "Latitude", col = "Genomic \nOffset", fill = "Genomic \nOffset")
(map_yrk_int_rda)

yrk_int_rda_inset <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_yrk_rda, mapping = aes(fill = var1.pred, col = var1.pred)) +
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,3.5)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,3.5)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting, aes(x = longitude, y = latitude, 
                                              fill = offset_yrk_sea), 
             shape = 21, size = 5) +
  geom_point(data = offsets_plotting[offsets_plotting$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude,
                                       fill = offset_yrk), 
             shape = 21, size = 9)+
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0, 3.5)) + # double check these values
  geom_point(data = offsets_plotting[offsets_plotting$site_name == "YORKRIVER",], 
             aes(x = longitude, y = latitude+0.2), fill = "deeppink", shape = 24, size = 7)+
  geom_label_repel(data = offsets_plotting[offsets_plotting$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, label = site_name),
                  nudge_x = 2.5,
                  nudge_y = 0.7,
                  fill = "white",
                  size = 9)+
  guides(fill = "none")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right') +
        xlim(-77.856476, -72.762787) +
        ylim(36.019557, 39.939163)
yrk_int_rda_inset
```

### GF

```{r}
map_lew_int_gf_af <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_lew_af, mapping = aes(fill = var1.pred, col = var1.pred)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting_gf, aes(x = lon, y = lat, 
                                              fill = offset_gf_af_lew), 
             shape = 21, size = 2) +
  geom_point(data = offsets_plotting_gf[offsets_plotting_gf$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=longitude, y=latitude, 
                                       fill = offset_gf_af_lew), 
             shape = 21, size = 4)+
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,0.021)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,0.021)) +
  geom_label_repel(data = offsets_plotting_gf[offsets_plotting_gf$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=longitude, y=latitude, 
                                       label = site_name),
                  nudge_x = -3,
                  nudge_y = 1,
                  fill = "white")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right')+
  labs(title = "Genomic Offset to \nLewisetta (GF AF)", x = "Longitude", y = "Latitude", col = "Genomic \nOffset", fill = "Genomic \nOffset")
(map_lew_int_gf_af)

lew_int_gf_af_inset <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_lew_af, mapping = aes(fill = var1.pred, col = var1.pred)) +
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,0.021)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,0.021)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting_gf, aes(x = lon, y = lat, 
                                              fill = offset_gf_af_lew), 
             shape = 21, size = 5) +
  geom_point(data = offsets_plotting_gf[offsets_plotting_gf$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, fill = offset_gf_af_lew), 
             shape = 21, size = 7)+
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0, 0.021)) + # double check these values
  geom_point(data = exp_site_latlon[exp_site_latlon$site_name == "LEW",], 
             aes(x = lon-0.2, y = lat), fill = "deeppink", shape = 24, size = 7)+
  geom_label_repel(data = offsets_plotting_gf[offsets_plotting_gf$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, label = site_name),
                  nudge_x = 2.5,
                  nudge_y = 0.4,
                  fill = "white",
                  size = 9)+
  guides(fill = "none")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right') +
        xlim(-77.856476, -72.762787) +
        ylim(36.019557, 39.939163)
lew_int_gf_af_inset

# put these together into single plot
#library(patchwork)
#map_lew_int_gf_af + inset_element(lew_int_gf_af_inset, left = 0.6, bottom = 0.6, right = 1, top = 1) # this requires changing the dimensions of the inset, come back to it

map_yrk_int_gf_af <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_yrk_af, mapping = aes(fill = var1.pred, col = var1.pred)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting_gf, aes(x = lon, y = lat, 
                                              fill = offset_gf_af_yrk), 
             shape = 21, size = 2) +
  geom_point(data = offsets_plotting_gf[offsets_plotting_gf$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=longitude, y=latitude, 
                                       fill = offset_gf_af_yrk), 
             shape = 21, size = 4)+
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,0.021)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,0.021)) +
  geom_label_repel(data = offsets_plotting_gf[offsets_plotting_gf$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=longitude, y=latitude, 
                                       label = site_name),
                  nudge_x = -3,
                  nudge_y = 1,
                  fill = "white")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right')+
  labs(title = "Genomic Offset to \nYork River (GF AF)", x = "Longitude", y = "Latitude", col = "Genomic \nOffset", fill = "Genomic \nOffset")
(map_yrk_int_gf_af)

yrk_int_gf_af_inset <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_yrk_af, mapping = aes(fill = var1.pred, col = var1.pred)) +
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,0.021)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,0.021)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = offsets_sea_plotting_gf, aes(x = lon, y = lat, 
                                              fill = offset_gf_af_yrk), 
             shape = 21, size = 5) +
  geom_point(data = offsets_plotting_gf[offsets_plotting_gf$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, fill = offset_gf_af_yrk), 
             shape = 21, size = 7)+
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0, 0.021)) + # double check these values
  geom_point(data = exp_site_latlon[exp_site_latlon$site_name == "YRK",], 
             aes(x = lon-0.2, y = lat), fill = "deeppink", shape = 24, size = 7)+
  geom_label_repel(data = offsets_plotting_gf[offsets_plotting_gf$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, label = site_name),
                  nudge_x = 2.5,
                  nudge_y = 0.4,
                  fill = "white",
                  size = 9)+
  guides(fill = "none")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right') +
        xlim(-77.856476, -72.762787) +
        ylim(36.019557, 39.939163)
yrk_int_gf_af_inset
```

### Environmental Distance

```{r}
map_lew_int_envdist <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_lew_envdist, mapping = aes(fill = var1.pred, col = var1.pred)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = envdist_sea_plotting, aes(x = Longitude_manual, y = Latitude_manual, 
                                              fill = Lewisetta), 
             shape = 21, size = 2) +
  geom_point(data = envdist_plotting[envdist_plotting$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x = longitude, y = latitude, 
                                       fill = Lewisetta), 
             shape = 21, size = 4)+
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,6)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,6)) +
  geom_label_repel(data = envdist_plotting[envdist_plotting$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x=Longitude_manual, y=Latitude_manual, label = site_name),
                  nudge_x = -3,
                  nudge_y = 1,
                  fill = "white")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right')+
  labs(title = "Environmental Distance to \nLewisetta", x = "Longitude", y = "Latitude", col = "Environmental \nDistance", fill = "Environmental \nDistance")
(map_lew_int_envdist)

lew_int_envdist_inset <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_lew_envdist, mapping = aes(fill = var1.pred, col = var1.pred)) +
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,6)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,6)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = envdist_sea_plotting, aes(x = Longitude_manual, y = Latitude_manual, 
                                              fill = Lewisetta), 
             shape = 21, size = 5) +
  geom_point(data = envdist_plotting[envdist_plotting$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x = longitude, y = latitude, 
                                       fill = Lewisetta), 
             shape = 21, size = 9)+
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0, 6)) +
  geom_point(data = envdist_plotting[envdist_plotting$site_name == "Lewisetta",], 
             aes(x = longitude-0.2, y = latitude), fill = "deeppink", shape = 24, size = 7)+
  geom_label_repel(data = envdist_plotting[envdist_plotting$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x = longitude, y = latitude, label = site_name),
                  nudge_x = 2.5,
                  nudge_y = 0.5,
                  fill = "white",
                  size = 9)+
  guides(fill = "none")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right') +
        xlim(-77.856476, -72.762787) +
        ylim(36.019557, 39.939163)
lew_int_envdist_inset

map_yrk_int_envdist <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_yrk_envdist, mapping = aes(col = var1.pred, fill = var1.pred)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = envdist_sea_plotting, aes(x = Longitude_manual, y = Latitude_manual, 
                                              fill = YorkRiver), 
             shape = 21, size = 2) +
  geom_point(data = envdist_plotting[envdist_plotting$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x = longitude, y = latitude, fill = YorkRiver), 
             shape = 21, size = 4)+
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,6)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,6)) +
  geom_label_repel(data = envdist_plotting[envdist_plotting$site_name %in% c("W1_TX", "W2_LA", "W3_FL", "W5_NH", "W6_ME"),], aes(x = longitude, y = latitude, 
                                       label = site_name),
                  nudge_x = -3,
                  nudge_y = 1,
                  fill = "white")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = "right")+
  labs(title = "Environmental Distance to \nYork River", x = "Longitude", y = "Latitude", col = "Environmental \nDistance", fill = "Environmental \nDistance")
(map_yrk_int_envdist)

yrk_int_envdist_inset <- ggplot(data = world) +
  theme_bw()+
  geom_sf(data = interpolated_yrk_envdist, mapping = aes(fill = var1.pred, col = var1.pred)) +
  scale_colour_viridis_c(option = "mako", direction = -1, limits = c(0,6)) +
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0,6)) +
  geom_sf(data = world_crop, fill = 'antiquewhite1') +
  geom_point(data = envdist_sea_plotting, aes(x = Longitude_manual, y = Latitude_manual, 
                                              fill = YorkRiver), 
             shape = 21, size = 5) +
  geom_point(data = envdist_plotting[envdist_plotting$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, fill = YorkRiver), 
             shape = 21, size = 9)+
  scale_fill_viridis_c(option = "mako", direction = -1, limits = c(0, 6)) + # double check these values
  geom_point(data = envdist_plotting[envdist_plotting$site_name == "YorkRiver",], 
             aes(x = longitude, y = latitude+0.2), fill = "deeppink", shape = 24, size = 7)+
  geom_label_repel(data = envdist_plotting[envdist_plotting$site_name %in% c("W4_VA", "S1_LOLA", "S2_DEBY"),], aes(x=longitude, y=latitude, label = site_name),
                  nudge_x = 2.5,
                  nudge_y = 0.7,
                  fill = "white",
                  size = 9)+
  guides(fill = "none")+
  theme(plot.title = element_text(size = 24), panel.grid.major = element_line(color = "aliceblue"),
        panel.background = element_rect(fill = "aliceblue"), legend.position = 'right') +
        xlim(-77.856476, -72.762787) +
        ylim(36.019557, 39.939163)
yrk_int_envdist_inset
```


## Export

```{r}
# export to ppt as editable vector graphic
doc <- read_pptx() %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = goFitLEA_plotfinalTsurv), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = goFitGFaf_plotfinalTsurv), location = ph_location_type(type = "body")) %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = goFitRDA_plotfinalTsurv), location = ph_location_type(type = "body")) %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = goFitEnvdist_plotfinalTsurv), location = ph_location_type(type = "body")) %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = goFitLEA_plotfinalTlen), location = ph_location_type(type = "body")) %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = goFitGFaf_plotfinalTlen), location = ph_location_type(type = "body")) %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = goFitRDA_plotfinalTlen), location = ph_location_type(type = "body")) %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(value = dml(ggobj = goFitEnvdist_plotfinalTlen), location = ph_location_type(type = "body"))
print(doc, target = "results/figures/GO_compare.pptx")
```

